# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false
paginate:            5
gems: [jekyll-paginate]
paginate_path: "page:num"

# Setup
title:               Not Fuchsia
tagline:             "Test blog for editing"
description:         "Testing blog for editing."
base-url:             "base-url"
baseurl:             ""
url:                 "https://notfuchsia.github.io"
github:              "https://www.github.com/notfuchsia"
timezone:            UTC

exclude: ["README.md", "OWNERS", "update_blog.sh"]

# Custom vars
version:             0.0.1

# Build settings
markdown: kramdown

# Authors
authors:
  adarob:
   display_name: Adam Roberts
   name: Adam Roberts
   email: adarob@google.com
   github: adarob
  cinjon:
   display_name: Cinjon Resnick
   name: Cinjon Resnick
   email: cinjon@google.com
   github: cinjon
  danabo:
   display_name: Dan Abolafia
   name: Dan Abolafia
   email: danabo@google.com
   twitter: danielabolafia
   github: danabo
  douglaseck:
   display_name: Douglas Eck
   name: Douglas Eck
   email: deck@google.com
   web: http://research.google.com/pubs/author39086.html
   twitter: douglas_eck
   github: douglaseck
  elliotwaite:
   display_name: Elliot Waite
   name: Elliot Waite
   email: elliotwaite@google.com
   github: elliotwaite
  fredbertsch:
   display_name: Fred Bertsch
   name: Fred Bertsch
   email: fredbertsch@google.com
   github: fredbertsch
  sageev:
   display_name: Sageev Oore
   name: Sageev Oore
   email: sageev@google.com
   github: osageev
  annahuang:
   display_name: Anna Huang
   name: Anna Huang
   email: chengzhiannahuang@gmail.com 
   github: annahuang
  natashamjaques:
   display_name: Natasha Jaques
   name: Natasha Jaques
   email: jaquesn@mit.edu 
   github: natashamjaques


